<a href="https://colab.research.google.com/github/mrinaligupta255/Python-Libraries-for-Data-Science/blob/master/Numpy_For_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basics of Numpy**

 

1.   Importing the library



In [0]:
import numpy as np



2. Creating a Numpy array



In [0]:
a1=np.array([1,2,3,4])  # a numpy array by converting python list to array
a2=np.arange(0,20,2) # create a numpy array starting from 0-20 by skipping 2 steps (here 20 is exclusive)

a3=np.linspace(2,10,4)# create a evenly spaced numpy array between given range with 4 elements(4 represent the no. of elements thatshould be present in the array)

print('a1:',a1)
print('a2:',a2)
print('a3:',a3)

a1: [1 2 3 4]
a2: [ 0  2  4  6  8 10 12 14 16 18]
a3: [ 2.          4.66666667  7.33333333 10.        ]


**Numpy array are faster in terms of compution and ease of manipulation than normal python arrays/list**

**np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)**

>>np.linspace ( ) has 6 parameters :

>>>start — Starting value of the sequence

>>>stop — Last value of the sequence

>>>num — Number of samples to be generated

>>>endpoint — This is a boolean value. If the value of endpoint is true, then stop is the last sample of the sequence. The default value of endpoint is true.

>>>retstep — Default value is true. If the value of retstep is true then return samples and steps(the difference between 2 samples)

>>>dtype — The type of array or matrices

**By default, np.linspace( ) created one dimensional array, if you want to create 2-Dimensional or 3-Dimensional matrices, you can use np.reshape ( ) with np.linspace .**

3. Properties of numpy array

>.size : returns no. of elements in an array

>.shape: returns the dimensions of array

>.dtype:returns type of elements in array

>.astype(dtype): returns an  array after converting the dtype of the array into given dtype

>np.info(): To view Documentation

In [0]:
print(a1.size)
print(a1.shape)
print(a1.dtype)
w=a1.astype(float)# It will return a array with the give dtype without changing the dtype of a1
print(a1.dtype)  # the dtype of a1 will not change
print(w.dtype)
print(np.info(np.eye))

4
(4,)
int64
int64
float64
None


**(4,) indicates that it is a 1-D array as it has only one dimension**

4. Reshaping the numpy array: no of elements will remain same

 Resize the numpy array :no of elements depends on the shape given
 >**ndarray.resize((n,m), refcheck=True)**   
 Changes array shape to nxm and fills new values with 0
 >>(n,m) : tuple of ints, or n ints
                Shape of resized array.

   >>refcheck : bool, optional

               If False, reference count will not be checked. Default is True.
               
        
 >> ##NOTES##
               
 >>>This reallocates space for the data area if necessary.

>>>Only contiguous arrays (data elements consecutive in memory) can be resized.

>>>The purpose of the reference count check is to make sure you do not use this array as a buffer for another Python object and then reallocate the memory. However, reference counts can increase in other ways so if you are sure that you have not shared the memory for this array with another Python object, then you may safely set refcheck to False.




In [0]:
a1=np.array([1,2,3,4])
a3=a1.reshape(2,2) # returns a matrix of shape 2x2 ...It does not change the dimensoin of a1
print(a3)
print('shape of a3:',a3.shape)
print('shape of a1:',a1.shape)

a2=np.arange(1,8,1)
print('a2:',a2)
a2.resize(6,6) # resize the given array and fill new values with 0, it changes a2 array itself
print('a2 after resizing:',a2)
print('shape of a2 after resizing:',a2.shape)

#a1.resize(9,9)  #this will cause error as as a1 is referenced to a3.Therfore usredchek=False to avoid checking the reference
a1.resize((9,9),refcheck=False)
print('a1 after resizing:',a1)


[[1 2]
 [3 4]]
shape of a3: (2, 2)
shape of a1: (4,)
a2: [1 2 3 4 5 6 7]
a2 after resizing: [[1 2 3 4 5 6]
 [7 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
shape of a2 after resizing: (6, 6)
a1 after resizing: [[1 2 3 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


**The dimension inside reshape should match with the array to be reshaped**


5.   np.zeros((n,m)) : **returns a nxm matrix with all zeros**

     np.ones((n,m)) : **returns a nxm matrix with all 1**

     np.eye(n): **returns a Identity matrix of shape nxn**
     
     np.full(shape, fill_value, dtype = None, order = ‘C’) : **returns a matrix of given shape with default values**
  



In [0]:
a4=np.zeros((3,4))
print(a4)
a5=np.eye(4)
print(a5)
a5=np.full((3,2),5)
print(a5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5 5]
 [5 5]
 [5 5]]


6. Numpy array slicing 

    x[start:end:step] 
    
      **'start'**:starting index

      **'end'**: end index(it will be exclusive)

      **'step'**: skipping by step 

In [0]:
a6=a2[2:10:3]
print(a2)
print(a6)

[[1 2 3 4 5 6]
 [7 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


**If any of the parameters are unspecified , they default to the values start=0, stop=size of dimension, step=1**

**When step Value is -ve then the default to the values of start=size of dimension, stop=0. start should be greater than the end**



In [0]:
a7=a2[::-1]  # reverse the array
print(a7)
a8=a2[6:2:-1]  # a8 will be having elements from index 6 to index 2(index 2 is exclusive) in reverse order
print(a8)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [7 0 0 0 0 0]
 [1 2 3 4 5 6]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


7.Copying of numpy arrays 

    One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies 

In [0]:
x_numpy=np.arange(0,20,3)
x_list=[0,3,6,9,12,15,18]
y=x_numpy[3:7]
z=x_list[3:7]
print('x:',x_numpy)
print('y:',y)
print('z:',z)
y[0]=100
z[0]=100
print('x_numpy:',x_numpy,'x_numpy is changed')
print('x_list:',x_list,'x_list is same')

x: [ 0  3  6  9 12 15 18]
y: [ 9 12 15 18]
z: [9, 12, 15, 18]
x_numpy: [  0   3   6 100  12  15  18] x_numpy is changed
x_list: [0, 3, 6, 9, 12, 15, 18] x_list is same


**This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.**

To create copy of the numpy array ,use copy() method

In [0]:
x=np.arange(0,20,3)
x1=x[3:7].copy()
x1[0]=100
print('x:',x)
print('x1:',x1)

x: [ 0  3  6  9 12 15 18]
x1: [100  12  15  18]


8. Axis in numpy array:
>>**An axis is similar to a dimension. For a 2-dimensional array, there are 2 axes: vertical and horizontal.When applying certain Numpy functions like np.mean(), we can specify what axis we want to calculate the values across.**

>>For axis=0, this means that we apply a function along each “column”, or all values that occur vertically.

>>For axis=1, this means that we apply a function along each “row”, or all values horizontally.

>>For n dimensions , nth dimension is collapsed and then operation is performed.

In [0]:
x=np.array([[1,2,3],[1,2,3]])
print(np.sum(x,axis=0)) ## axis 0 will collapse the first dimension i.e rows and then will perform the sum.
print(np.sum(x,axis=1)) ## axis 1 will collapse the senond dimension i.e columns and will perform sum operation.

[2 4 6]
[6 6]


9.Adding/Removing elements from numpy array

>>numpy.append(arr, values, axis=None):**returns a copy of arr with appended values to the end of the array**

>>>axis=The axis along which values are appended. If axis is not given, both arr and values are flattened before use.

>>numpy.insert(arr, obj, values, axis=None): **returns a copy of arr with values inserted along the given axis before the given indices.**

>>>obj : int, slice or sequence of ints

>>>>Object that defines the index or indices before which values is inserted.

>>>axis : int, optional
>>>>Axis along which to insert values. If axis is None then arr is flattened first.

>>numpy.delete(arr, obj, axis=None):**Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].**

In [0]:
#append

print('-----APPEND----')
x=np.array([[1,2,3]])
w=np.append(x,[[1,2,3],[3,4,5],[7,8,9]])
y=np.append(x,[[4]],axis=1)
z=np.append(x,[[1,2,3],[3,4,5],[7,8,9]],axis=0)
print('not changed,x:',x)
print('no axis is given...so output is flattened after appending:',w)
print('appening in axis 1:',y)
print('appending in axis 0:',z)


#insert
print('----INSERT----------')
x=np.array([[1,2,3]])
w=np.insert(x,1,[7,8,9])
y=np.insert(x,1,[7,8,9],axis=0)
z=np.insert(x,2,[[4]],axis=1)
print('not changed,x:',x)
print('no axis is given...so output is flattened after insertion:',w)
print('inserting in axis 1:',y)
print('inserting in axis 0:',z)

#delete

print('---------Delete---------')
x=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
w=np.delete(x,1)
y=np.delete(x,1,axis=0)
z=np.delete(x,2,axis=1)
print('not changed,x:',x)
print('no axis is given...so output is flattened after deletion:',w)
print('deletion in axis 1:',y)
print('deletion in axis 0:',z)



-----APPEND----
not changed,x: [[1 2 3]]
no axis is given...so output is flattened after appending: [1 2 3 1 2 3 3 4 5 7 8 9]
appening in axis 1: [[1 2 3 4]]
appending in axis 0: [[1 2 3]
 [1 2 3]
 [3 4 5]
 [7 8 9]]
----INSERT----------
not changed,x: [[1 2 3]]
no axis is given...so output is flattened after insertion: [1 7 8 9 2 3]
inserting in axis 1: [[1 2 3]
 [7 8 9]]
inserting in axis 0: [[1 2 4 3]]
---------Delete---------
not changed,x: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
no axis is given...so output is flattened after deletion: [ 1  3  4  5  6  7  8  9 10 11 12]
deletion in axis 1: [[ 1  2  3  4]
 [ 9 10 11 12]]
deletion in axis 0: [[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


10. Combining/splitting of numpy array

>>numpy.concatenate((a1, a2, ...), axis=0, out=None):**Join a sequence of arrays along an existing axis.**


>>>a1, a2, … : sequence of array_like
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

>>>axis : int, optional
The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

>>>out : ndarray, optional
If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.


>>numpy.split(ary, indices_or_sections, axis=0):**Split an array into multiple sub-arrays**

>>>ary : ndarray
>>>>Array to be divided into sub-arrays.

>>>indices_or_sections : int or 1-D array
>>>>If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

>>>>If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in

>>>>>ary[:2]
>>>>>ary[2:3]
>>>>>ary[3:]


>>>>**If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.**

>>>>axis : int, optional
>>>>>The axis along which to split, default is 0.


>>numpy.hsplit(ary, indices_or_sections):**Split an array into multiple sub-arrays horizontally (column-wise).**

>>numpy.vsplit(ary, indices_or_sections):**Split an array into multiple sub-arrays vertically (row-wise).**

In [0]:
#concatenate
print('----Concatenate----')
x=np.array([[1,2,3],[4,5,6]])   ## 2x3
y=np.array([[1],[2]])        ##2x1
z=np.concatenate((x,y),axis=1)    ## x and y should have same shape except the dimension of the axis i.e column here(axis=1)
print('x:',x)
print('y:',y)
print(' concat when axis=1:',z)

#split

print('----split----')
x=np.arange(0,20,2)
y=np.split(x,2,axis=0)
z=np.split(x, [3, 5, 6, 10,15])
print('y:',y)
print('z:',z)

#hsplit  splitting column-wise
print('----hsplit---')
x=np.arange(0,20,2)
y=np.hsplit(x,2)
z=np.hsplit(x, np.array([3, 6]))
print('y:',y)
print('z:',z)

----Concatenate----
x: [[1 2 3]
 [4 5 6]]
y: [[1]
 [2]]
 concat when axis=1: [[1 2 3 1]
 [4 5 6 2]]
----split----
y: [array([0, 2, 4, 6, 8]), array([10, 12, 14, 16, 18])]
z: [array([0, 2, 4]), array([6, 8]), array([10]), array([12, 14, 16, 18]), array([], dtype=int64), array([], dtype=int64)]
----hsplit---
y: [array([0, 2, 4, 6, 8]), array([10, 12, 14, 16, 18])]
z: [array([0, 2, 4]), array([ 6,  8, 10]), array([12, 14, 16, 18])]


11. Scalar math

>>np.add(arr,1) | Add 1 to each array element

>>np.subtract(arr,2) | Subtract 2 from each array element

>>np.multiply(arr,3) | Multiply each array element by 3

>>np.divide(arr,4) | Divide each array element by 4 (returns np.nan for division by zero)

>>np.power(arr,5) | Raise each array element to the 5th power

12. Vector math

  np.add(arr1,arr2) | Elementwise add arr2 to arr1

  np.subtract(arr1,arr2) | Elementwise subtract arr2 from arr1

  np.multiply(arr1,arr2) | Elementwise multiply arr1 by arr2

  np.divide(arr1,arr2) | Elementwise divide arr1 by arr2

  np.power(arr1,arr2) | Elementwise raise arr1 raised to the power of arr2

  np.array_equal(arr1,arr2) | Returns True if the arrays have the same elements and shape

  np.sqrt(arr) | Square root of each element in the array

  np.sin(arr) | Sine of each element in the array

  np.log(arr) | Natural log of each element in the array

  np.abs(arr) | Absolute value of each element in the array

  np.ceil(arr) | Rounds up to the nearest int

  np.floor(arr) | Rounds down to the nearest int

  np.round(arr) | Rounds to the nearest int

13. Statistics

    np.mean(arr,axis=0) | Returns mean along specific axis
    
    arr.sum() | Returns sum of arr
    
    arr.min() | Returns minimum value of arr
    
    arr.max(axis=0) | Returns maximum value of specific axis
    
    np.var(arr) | Returns the variance of array
    
    np.std(arr,axis=1) | Returns the standard deviation of specific axis
    
    arr.corrcoef() | Returns correlation coefficient of array

  14. *numpy.random.seed*
  numpy.random.seed(seed=None) Seed the generator.

  This method is called when RandomState is initialized. It can be called again to re-seed the generator. For details, see RandomState.

  Parameters:	
  seed : int or 1-d array_like, optional
  Seed for RandomState. Must be convertible to 32 bit unsigned integers.



In [8]:
import numpy as np
np.random.seed(0)
print(np.random.rand(10))
np.random.seed(0)
print(np.random.rand(10))
np.random.seed(3)
print(np.random.rand(10))
np.random.seed(0)
print(np.random.rand(10))
np.random.seed(3)
print(np.random.rand(10))



[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
 0.12558531 0.20724288 0.0514672  0.44080984]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
 0.12558531 0.20724288 0.0514672  0.44080984]
