<a href="https://colab.research.google.com/github/mrinaligupta255/Python-Libraries-for-Data-Science/blob/master/Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas
 is used for data manipulation, analysis and cleaning. Python pandas is well suited for different kinds of data, such as: 

Tabular data with heterogeneously-typed columns
Ordered and unordered time series data
Arbitrary matrix data with row & column labels
Unlabelled data
Any other form of observational or statistical data sets

In [0]:
import pandas as pd
import numpy as np

##Data Structures in pandas

#1. Series

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. 

    s = pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
Here, data can be many different things:

    a Python dict
    an ndarray
    a scalar value (like 5)
The passed index is a list of axis labels. 

In [2]:
 s=pd.Series(np.random.randn(5))
print('Without indexgiven',s)
 s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
 print('with index given',s)

Without indexgiven 0    0.558703
1    1.119122
2   -0.868704
3   -0.052315
4   -0.300475
dtype: float64
with index given a    1.165556
b    1.189044
c    1.762687
d    1.263990
e    0.448424
dtype: float64


**Note:** pandas supports non-unique index values. If an operation that does not support duplicate index values is attempted, an exception will be raised at that time. The reason for being lazy is nearly all performance-based (there are many instances in computations, like parts of GroupBy, where the index is not used).

In [4]:
s = pd.Series(np.random.randn(5), index=['a', 'a', 'a', 'd', 'e'])
print('with index given',s['a'])

with index given a    0.092236
a   -0.349679
a    0.517532
dtype: float64


If an index is passed, the values in data corresponding to the labels in the index will be pulled out from the dictonary while creating series from a dictonary.

In [7]:
d = {'a' : 0., 'b' : 1., 'c' : 2.}
s=pd.Series(d)
print(s)
s=pd.Series(d, index=['b', 'c', 'd', 'a'],name='dict_series')
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64
b    1.0
c    2.0
d    NaN
a    0.0
Name: dict_series, dtype: float64


**Note:** NaN (not a number) is the standard missing data marker used in pandas.

##2. DataFrame

DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. Like Series, DataFrame accepts many different kinds of input:

Dict of 1D ndarrays, lists, dicts, or Series

    2-D numpy.ndarray
    Structured or record ndarray
    A Series
    Another DataFrame

In [8]:
 data = {'Country': ['Belgium', 'India', 'Brazil'],
 'Capital': ['Brussels', 'New Delhi', 'Brasília'],
 'Population': [11190846, 1303171035, 207847528]}
 df = pd.DataFrame(data,
 columns=['Country', 'Capital', 'Population'])
 print(df)


   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528


Along with the data, you can optionally pass index (row labels) and columns (column labels) arguments. If you pass an index and / or columns, you are guaranteeing the index and / or columns of the resulting DataFrame. Thus, a dict of Series plus a specific index will discard all data not matching up to the passed index.

If axis labels are not passed, they will be constructed from the input data based on common sense rules.

In [10]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
   'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df=pd.DataFrame(d)
print(df)
df=pd.DataFrame(d, index=['d', 'b', 'a'])
print(df)
df=pd.DataFrame(d, index=['d', 'b', 'a'], columns=['two', 'three'])
print(df)

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0
   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN


The row and column labels can be accessed respectively by accessing the index and columns attributes:

**Note: When a particular set of columns is passed along with a dict of data, the passed columns override the keys in the dict.**

In [12]:
print(df.index)
print(df.columns)

Index(['d', 'b', 'a'], dtype='object')
Index(['two', 'three'], dtype='object')


##Importing Data
    pd.read_csv(filename) | From a CSV file , user header=None if the file is not having columns name
    pd.read_table(filename) | From a delimited text file (like TSV)
    pd.read_excel(filename) | From an Excel file
    pd.read_sql(query, connection_object) | Read from a SQL table/database
    pd.read_json(json_string) | Read from a JSON formatted string, URL or file.
    pd.read_html(url) | Parses an html URL, string or file and extracts tables to a list of dataframes
    pd.read_clipboard() | Takes the contents of your clipboard and passes it to read_table()
    pd.DataFrame(dict) | From a dict, keys for columns names, values for data as lists

##Exporting Data
    df.to_csv(filename) | Write to a CSV file
    df.to_excel(filename) | Write to an Excel file
    df.to_sql(table_name, connection_object) | Write to a SQL table
    df.to_json(filename) | Write to a file in JSON format

Viewing/Inspecting Data

    df.head(n) | First n rows of the DataFrame
    df.tail(n) | Last n rows of the DataFrame
    df.shape | Number of rows and columns
    df.info() | Index, Datatype and Memory information
    df.describe() | Summary statistics for numerical columns
    s.value_counts(dropna=False) | View unique values and counts
    df.apply(pd.Series.value_counts) | Unique values and counts for all columns

    

##Selection
    df.values| Return a Numpy representation of the DataFrame.
    df[1:4] | get subset of a dataframe
    df[col] | Returns column with label col as Series
    df[[col1, col2]] | Returns columns as a new DataFrame
    s.iloc[0] | Selection by position
    s.loc['index_one'] | Selection by index
    df.iloc[0,:] | First row
    df.iloc[0,0] | First element of first column

**loc** gets rows (or columns) with particular labels from the index.

**iloc** gets rows (or columns) at particular positions in the index (so it only takes integers).

In [47]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
   'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),'three':pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
   }
df=pd.DataFrame(d)
print('dataframe')
print(df)
print('subset of dataframe')
print(df[1:3])
print('values of a dataframe')
print(df.values) # will give a numpy array representation
print()
print(df['one'])
print('selection by index')
print(df.loc['a'])
print(df[['one','three']])
print(df.iloc[1].values)
print(df[1:4])



dataframe
   one  two  three
a  1.0  1.0      1
b  2.0  2.0      2
c  3.0  3.0      3
d  NaN  4.0      4
e  NaN  NaN      5
subset of dataframe
   one  two  three
b  2.0  2.0      2
c  3.0  3.0      3
values of a dataframe
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [nan  4.  4.]
 [nan nan  5.]]

a    1.0
b    2.0
c    3.0
d    NaN
e    NaN
Name: one, dtype: float64
selection by index
one      1.0
two      1.0
three    1.0
Name: a, dtype: float64
   one  three
a  1.0      1
b  2.0      2
c  3.0      3
d  NaN      4
e  NaN      5
[2. 2. 2.]
   one  two  three
b  2.0  2.0      2
c  3.0  3.0      3
d  NaN  4.0      4


##Data Cleaning
    df.columns = ['a','b','c'] | Rename columns
    pd.isnull() | Checks for null Values, Returns Boolean Arrray
    pd.notnull() | Opposite of pd.isnull()
    df.dropna() | Drop all rows that contain null values
    df.dropna(axis=1) | Drop all columns that contain null values
    df.dropna(axis=1,thresh=n) | Drop all rows have have less than n non null values
    df.fillna(x) | Replace all null values with x
    s.fillna(s.mean()) | Replace all null values with the mean (mean can be replaced with almost any function from the statistics module)
    s.astype(float) | Convert the datatype of the series to float
    s.replace(1,'one') | Replace all values equal to 1 with 'one'
    s.replace([1,3],['one','three']) | Replace all 1 with 'one' and 3 with 'three'
    df.rename(columns=lambda x: x + 1) | Mass renaming of columns
    df.rename(columns={'old_name': 'new_ name'}) | Selective renaming
    df.set_index('column_one') | Change the index
    df.rename(index=lambda x: x + 1) | Mass renaming of index

##Filter, Sort, and Groupby
    df[df[col] > 0.5] | Rows where the column col is greater than 0.5
    df[(df[col] > 0.5) & (df[col] < 0.7)] | Rows where 0.7 > col > 0.5
    df.sort_values(col1) | Sort values by col1 in ascending order
    df.sort_values(col2,ascending=False) | Sort values by col2 in descending order
    df.sort_values([col1,col2],ascending=[True,False]) | Sort values by col1 in ascending order then col2 in descending order
    df.groupby(col) | Returns a groupby object for values from one column
    df.groupby([col1,col2]) | Returns groupby object for values from multiple columns
    df.groupby(col1)[col2] | Returns the mean of the values in col2, grouped by the values in col1 (mean can be replaced with almost any function from the statistics module)
    df.pivot_table(index=col1,values=[col2,col3],aggfunc=mean) | Create a pivot table that groups by col1 and calculates the mean of col2 and col3
    df.groupby(col1).agg(np.mean) | Find the average across all columns for every unique col1 group
    df.apply(np.mean) | Apply the function np.mean() across each column
    nf.apply(np.max,axis=1) | Apply the function np.max() across each row

##Join/Combine
    df1.append(df2) | Add the rows in df1 to the end of df2 (columns should be identical)
    pd.concat([df1, df2],axis=1) | Add the columns in df1 to the end of df2 (rows should be identical)
    df1.join(df2,on=col1,how='inner') | SQL-style join the columns in df1 with the columns on df2 where the rows for
    col have identical values. 'how' can be one of 'left', 'right', 'outer', 'inner'

##Statistics

These can all be applied to a series as well.

    df.describe() | Summary statistics for numerical columns
    df.mean() | Returns the mean of all columns
    df.corr() | Returns the correlation between columns in a DataFrame
    df.count() | Returns the number of non-null values in each DataFrame column
    df.max() | Returns the highest value in each column
    df.min() | Returns the lowest value in each column
    df.median() | Returns the median of each column
    df.std() | Returns the standard deviation of each column